package net.pms.configuration;

import java.io.File;

import net.pms.api.PmsCore;
import net.pms.io.SystemUtils;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.inject.assistedinject.Assisted;
import com.google.inject.assistedinject.AssistedInject;

public class WindowsRegistryProgramPaths implements ProgramPaths {
	private static final Logger logger = LoggerFactory.getLogger(WindowsRegistryProgramPaths.class);
	private final ProgramPaths defaults;
	private final PmsCore pmsCore;

	/**
	 * Interface for a factory to be generated by Guice, using <a
	 * href="https://code.google.com/p/google-guice/wiki/AssistedInject">
	 * AssistedInject</a>.
	 */
	public interface Factory {
		public WindowsRegistryProgramPaths create(ProgramPaths defaults);
	}

	@AssistedInject
	WindowsRegistryProgramPaths(PmsCore pmsCore, @Assisted ProgramPaths defaults) {
		this.pmsCore = pmsCore;
		this.defaults = defaults;
	}

	@Override
	public String getEac3toPath() {
		return defaults.getEac3toPath();
	}

	@Override
	public String getFfmpegPath() {
		return defaults.getFfmpegPath();
	}

	@Override
	public String getFlacPath() {
		return defaults.getFlacPath();
	}

	@Override
	public String getMencoderPath() {
		return defaults.getMencoderPath();
	}

	@Override
	public String getMplayerPath() {
		return defaults.getMplayerPath();
	}

	@Override
	public String getTsmuxerPath() {
		return defaults.getTsmuxerPath();
	}

	@Override
	public String getVlcPath() {
		SystemUtils registry = pmsCore.getRegistry();
		if (registry.getVlcp() != null) {
			String vlc = registry.getVlcp();
			String version = registry.getVlcv();
			if (new File(vlc).exists() && version != null) {
				logger.debug("Found VLC version " + version + " in Windows Registry: " + vlc);
				return vlc;
			}
		}
		return defaults.getVlcPath();
	}

	@Override
	public String getDCRaw() {
		return defaults.getDCRaw();
	}
	
	@Override
	public String getIMConvertPath() {
		return defaults.getIMConvertPath();
	}
}
