/*
 * PS3 Media Server, for streaming any medias to your PS3.
 * Copyright (C) 2008  A.Brochard
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2
 * of the License only.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package net.pms.dlna;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;

import net.pms.api.PmsConfiguration;
import net.pms.api.PmsCore;
import net.pms.di.InjectionHelper;
import net.pms.formats.FormatFactory;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.inject.assistedinject.Assisted;
import com.google.inject.assistedinject.AssistedInject;

import de.innosystec.unrar.Archive;
import de.innosystec.unrar.exception.RarException;
import de.innosystec.unrar.rarfile.FileHeader;

public class RarredFile extends DLNAResource {
	private static final Logger logger = LoggerFactory.getLogger(RarredFile.class);
	private File f;
	private Archive rarFile;

	/**
	 * Interface for a factory to be generated by Guice, using <a
	 * href="https://code.google.com/p/google-guice/wiki/AssistedInject">
	 * AssistedInject</a>.
	 */
	public interface Factory {
		public RarredFile create(File file);
	}

	/**
	 * Temporary constructor to help with transition to DI.
	 * @deprecated Use {@link #RarredFile(PmsCore, PmsConfiguration, net.pms.dlna.RarredEntry.Factory, File)} instead.
	 */
	@Deprecated
	public RarredFile(File f) {
		this(InjectionHelper.getInjector().getInstance(PmsCore.class),
				InjectionHelper.getInjector().getInstance(PmsConfiguration.class),
				InjectionHelper.getInjector().getInstance(RarredEntry.Factory.class),
				InjectionHelper.getInjector().getInstance(FormatFactory.class),
				f);
	}

	@AssistedInject
	public RarredFile(PmsCore pmsCore, PmsConfiguration configuration,
			RarredEntry.Factory rarredEntryFactory, FormatFactory formatFactory,
			@Assisted File f) {
		super(pmsCore, configuration, formatFactory);
		this.f = f;
		setLastmodified(f.lastModified());
		try {
			rarFile = new Archive(f);
			List<FileHeader> headers = rarFile.getFileHeaders();
			for (FileHeader fh : headers) {
				//if (fh.getFullUnpackSize() < MAX_ARCHIVE_ENTRY_SIZE && fh.getFullPackSize() < MAX_ARCHIVE_ENTRY_SIZE)
				addChild(rarredEntryFactory.create(fh.getFileNameString(), f, fh.getFileNameString(), fh.getFullUnpackSize()));
			}
			rarFile.close();
		} catch (RarException e) {
			logger.error(null, e);
		} catch (IOException e) {
			logger.error(null, e);
		}
	}

	public InputStream getInputStream() throws IOException {
		return new FileInputStream(f);
	}

	public String getName() {
		return f.getName();
	}

	public long length() {
		return f.length();
	}

	public boolean isFolder() {
		return true;
	}

	public long lastModified() {
		return 0;
	}

	@Override
	public String getSystemName() {
		return f.getAbsolutePath();
	}

	@Override
	public boolean isValid() {
		boolean t = false;
		try {
			t = f.exists() && !rarFile.isEncrypted();
		} catch (Throwable th) {
			logger.debug("Caught exception", th);
		}
		return t;
	}
}
